# Generated by Django 5.1.4 on 2025-01-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abtract_page_size',
            field=models.IntegerField(default=27),
        ),
        migrations.AddField(
            model_name='user',
            name='abtract_start_page',
            field=models.IntegerField(default=1),
        ),
    ]
