# Generated by Django 5.1.4 on 2025-01-23 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_abtract_page_size_user_abtract_start_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_code',
            field=models.CharField(default=datetime.datetime(2025, 1, 23, 12, 3, 15, 864318, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
