# Generated by Django 5.1.4 on 2025-01-23 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
